// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';

export function Add(arg1:string,arg2:string):Promise<void>;

export function Del(arg1:number):Promise<void>;

export function Done(arg1:number):Promise<void>;

export function Done_off(arg1:number):Promise<void>;

export function Get():Promise<Array<task.Item>>;

export function Get_done():Promise<Array<task.Item>>;
