// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['main']['App']['Add'](arg1, arg2);
}

export function Del(arg1) {
  return window['go']['main']['App']['Del'](arg1);
}

export function Done(arg1) {
  return window['go']['main']['App']['Done'](arg1);
}

export function Done_off(arg1) {
  return window['go']['main']['App']['Done_off'](arg1);
}

export function Get() {
  return window['go']['main']['App']['Get']();
}

export function Get_done() {
  return window['go']['main']['App']['Get_done']();
}
